# Generated by Django 5.0.14 on 2026-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_counterstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterstaff',
            name='role',
            field=models.CharField(choices=[('staff', 'Operator'), ('supervisor', 'Counter'), ('counting', 'Counting Login'), ('admin', 'Super Admin')], default='staff', max_length=20),
        ),
    ]
