# Generated by Django 5.0.14 on 2026-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_counterstaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterstaff',
            name='role',
            field=models.CharField(choices=[('supervisor', 'Counter'), ('counting', 'Counting'), ('admin', 'Super Admin')], default='supervisor', max_length=20),
        ),
    ]
