# Generated by Django 5.0.14 on 2026-08-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_counterstaff_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterstaff',
            name='designation',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('company_secretary', 'Company Secretary')], help_text='Display label only, for admin-role logins. Does not affect permissions.', max_length=30),
        ),
    ]
