# Generated by Django 5.0.14 on 2026-08-01 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_customer_code'], name='audit_audit_entity__f6ba78_idx'),
        ),
    ]
