# Generated by Django 5.0.14 on 2026-08-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_card_number', models.CharField(db_index=True, max_length=50)),
                ('reader_name', models.CharField(blank=True, max_length=100)),
                ('tapped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-tapped_at'],
                'indexes': [models.Index(fields=['access_card_number'], name='sipass_inte_access__14b2ee_idx'), models.Index(fields=['tapped_at'], name='sipass_inte_tapped__5fb164_idx')],
            },
        ),
    ]
