# Generated by Django 5.0.14 on 2026-07-23 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid_reader_name', models.CharField(max_length=100, unique=True)),
                ('counter_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter_mapping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
