# Generated by Django 5.0.14 on 2026-07-28 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthRepChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50)),
                ('old_representative_name', models.CharField(blank=True, max_length=255)),
                ('old_access_card_number', models.CharField(blank=True, max_length=50)),
                ('new_representative_name', models.CharField(max_length=255)),
                ('new_access_card_number', models.CharField(blank=True, max_length=50)),
                ('new_photo', models.ImageField(blank=True, null=True, upload_to='auth_rep_photos/')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='auth_rep_documents/')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BallotPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_type', models.CharField(choices=[('category', 'Category'), ('exclusive', 'Exclusive')], max_length=10, unique=True)),
                ('total_ballots', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CounterBallotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_allocations', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='ballots.ballotpool')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCodeAllotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_card_number', models.CharField(max_length=50)),
                ('customer_code', models.CharField(max_length=50)),
                ('entity_name', models.CharField(blank=True, max_length=255)),
                ('roll_type', models.CharField(choices=[('category', 'Category'), ('exclusive', 'Exclusive')], max_length=10)),
                ('ballots_allotted', models.PositiveIntegerField(default=1)),
                ('allotted_at', models.DateTimeField(auto_now_add=True)),
                ('allotted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-allotted_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectoralRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_type', models.CharField(choices=[('category', 'Category'), ('exclusive', 'Exclusive')], max_length=10)),
                ('membership_no', models.CharField(max_length=50)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_name', models.CharField(max_length=255)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('representative_email', models.CharField(blank=True, max_length=255)),
                ('category_tier', models.CharField(blank=True, choices=[('I', 'Category I'), ('II', 'Category II'), ('III', 'Category III')], max_length=3, null=True)),
                ('ballot_entitlement', models.PositiveIntegerField(default=1)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['roll_type'], name='ballots_ele_roll_ty_4a41dd_idx'), models.Index(fields=['membership_no'], name='ballots_ele_members_fa462e_idx'), models.Index(fields=['customer_code'], name='ballots_ele_custome_fd3240_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='electoralroll',
            constraint=models.UniqueConstraint(fields=('roll_type', 'membership_no'), name='unique_roll_membership'),
        ),
        migrations.AddIndex(
            model_name='authrepchange',
            index=models.Index(fields=['customer_code'], name='ballots_aut_custome_fa3b3f_idx'),
        ),
        migrations.AddConstraint(
            model_name='counterballotallocation',
            constraint=models.UniqueConstraint(fields=('pool', 'counter'), name='unique_counter_pool_allocation'),
        ),
        migrations.AddIndex(
            model_name='customercodeallotment',
            index=models.Index(fields=['access_card_number'], name='ballots_cus_access__8bb794_idx'),
        ),
        migrations.AddIndex(
            model_name='customercodeallotment',
            index=models.Index(fields=['allotted_at'], name='ballots_cus_allotte_2b5f50_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercodeallotment',
            constraint=models.UniqueConstraint(fields=('customer_code',), name='unique_allotment_per_customer_code'),
        ),
    ]
