# Generated by Django 5.0.14 on 2026-07-29 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0002_drop_stale_used_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercodeallotment',
            name='eligibility_remark_at_allotment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customercodeallotment',
            name='fee_status_at_allotment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customercodeallotment',
            name='membership_status_at_allotment',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='customercodeallotment',
            name='voting_eligibility_source',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='VotingEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['customer_code'], name='ballots_vot_custome_b94739_idx')],
            },
        ),
    ]
