# Generated by Django 5.0.14 on 2026-07-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0003_customercodeallotment_eligibility_remark_at_allotment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('voting_done', models.BooleanField(default=False)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['customer_code'], name='ballots_vot_custome_7928de_idx')],
            },
        ),
    ]
