# Generated by Django 5.0.14 on 2026-08-01 06:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0004_votingstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customercodeallotment',
            index=models.Index(fields=['roll_type'], name='ballots_cus_roll_ty_44bcf9_idx'),
        ),
        migrations.AddIndex(
            model_name='customercodeallotment',
            index=models.Index(fields=['allotted_by', 'roll_type'], name='ballots_cus_allotte_358c80_idx'),
        ),
    ]
