# Generated by Django 5.0.14 on 2026-08-01 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0005_customercodeallotment_ballots_cus_roll_ty_44bcf9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customercodeallotment',
            index=models.Index(fields=['entity_name'], name='ballots_cus_entity__12a64b_idx'),
        ),
    ]
