# Generated by Django 5.0.14 on 2026-08-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0006_customercodeallotment_ballots_cus_entity__12a64b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='authrepchange',
            name='new_credential_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
