# Generated by Django 5.0.14 on 2026-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0007_authrepchange_new_credential_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercodeallotment',
            name='membership_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
