# Generated by Django 5.0.14 on 2026-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0008_customercodeallotment_membership_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoralroll',
            name='final_eligibility_status',
            field=models.BooleanField(default=False, help_text="From Excel column 'Final Eligibility Status'. This is the client's own pre-calculated AND of the fields above. Defaults to False (not eligible) so a member is never accidentally treated as eligible before this is explicitly imported as True."),
        ),
        migrations.AddField(
            model_name='electoralroll',
            name='membership_fees_paid',
            field=models.BooleanField(blank=True, help_text="From Excel column 'Membership Fees Paid upto <date>'. Null means not yet imported/unknown for this row.", null=True),
        ),
        migrations.AddField(
            model_name='electoralroll',
            name='outstanding_clear',
            field=models.BooleanField(blank=True, help_text="From Excel column 'Outstanding Clear as on date?'. Category roll only -- always null for Exclusive roll rows.", null=True),
        ),
    ]
