# Generated by Django 5.0.14 on 2026-07-28 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('category', 'Category Member'), ('exclusive', 'Exclusive Member')], default='category', max_length=20)),
                ('election_year', models.CharField(max_length=20)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Counting order. Lower numbers are counted first.')),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('in_progress', 'Counting In Progress'), ('completed', 'Counting Completed')], default='inactive', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Election categories',
                'ordering': ['election_year', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.PositiveIntegerField()),
                ('candidate_name', models.CharField(max_length=255)),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='counting.electioncategory')),
            ],
            options={
                'ordering': ['category', 'serial_no'],
            },
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_no', models.PositiveIntegerField()),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='counting.electioncategory')),
            ],
            options={
                'ordering': ['category', 'ballot_no'],
            },
        ),
        migrations.CreateModel(
            name='BallotVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='counting.ballot')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='counting.candidate')),
            ],
            options={
                'indexes': [models.Index(fields=['candidate'], name='counting_ba_candida_0daa52_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='ballotvote',
            constraint=models.UniqueConstraint(fields=('ballot', 'candidate'), name='unique_vote_per_ballot_candidate'),
        ),
        migrations.AddConstraint(
            model_name='electioncategory',
            constraint=models.UniqueConstraint(fields=('election_year', 'name'), name='unique_category_per_year'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('category', 'serial_no'), name='unique_candidate_serial_per_category'),
        ),
        migrations.AddIndex(
            model_name='ballot',
            index=models.Index(fields=['category', 'ballot_no'], name='counting_ba_categor_4b6afe_idx'),
        ),
        migrations.AddConstraint(
            model_name='ballot',
            constraint=models.UniqueConstraint(fields=('category', 'ballot_no'), name='unique_ballot_no_per_category'),
        ),
    ]
