# Generated by Django 5.0.14 on 2026-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='membership_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
