# Generated by Django 5.0.14 on 2026-08-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0002_candidate_membership_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electioncategory',
            name='kind',
            field=models.CharField(choices=[('category', 'Category Member'), ('exclusive', 'Exclusive Member'), ('women', 'Women')], default='category', max_length=20),
        ),
    ]
