# Generated by Django 5.0.14 on 2026-07-23 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityVotingExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('voting_eligibility_remark', models.TextField(blank=True)),
                ('total_ballot_category', models.PositiveIntegerField(default=0)),
                ('total_ballot_exclusive', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50)),
                ('representative_name', models.CharField(blank=True, max_length=255)),
                ('access_card_number', models.CharField(blank=True, max_length=50)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified_sent', 'Verified and Sent for Vote'), ('not_eligible', 'Not Eligible to Vote')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_counter', models.CharField(blank=True, max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['customer_code'], name='verificatio_custome_7377b5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='verificationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('verification_status', 'verified_sent')), fields=('customer_code',), name='unique_verified_sent_per_customer_code'),
        ),
    ]
