# Generated by Django 5.0.14 on 2026-07-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KycSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kyc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('submission_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kyc_submissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KycUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('sap_code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('access_code', models.CharField(blank=True, max_length=50, null=True)),
                ('elegible_user', models.BooleanField(default=False)),
                ('profile_picture', models.CharField(blank=True, max_length=500, null=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MembersMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_no', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_code', models.CharField(max_length=50, unique=True)),
                ('member_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('member_category', models.CharField(blank=True, max_length=100, null=True)),
                ('membership_fees_status', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('tan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('dispute_status', models.CharField(blank=True, max_length=50, null=True)),
                ('folio_no', models.CharField(blank=True, max_length=50, null=True)),
                ('active_status', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'members_master',
                'managed': False,
            },
        ),
    ]
