# Generated by Django 5.0.14 on 2026-08-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc_portal', '0002_onlinepayment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlinepayment',
            table='payments',
        ),
    ]
